# Supermarket Sales Analysis

Analisis data penjualan supermarket untuk memahami pola penjualan, performa produk, dan performa cabang.

## Objective
Project ini bertujuan untuk mengeksplorasi data transaksi supermarket
dan menemukan pola serta insight yang dapat membantu memahami performa penjualan.

## 1. Import Libraries & Load Data
Pertama, kita mengimpor library yang diperlukan dan membaca dataset.

In [ ]:
import pandas as pd

data = pd.read_csv ("supermarket.csv")

## 2. Understanding the Data
Sebelum melakukan analisis, kita akan memahami struktur, isi, tipe data, dan karakteristik dataset.

In [6]:
import pandas as pd

data = pd.read_csv ("/kaggle/input/datasets/ismatkhan121/supermarket-sales-dataset/supermarket.csv")

data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 9800 entries, 0 to 9799
Data columns (total 18 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   Row ID         9800 non-null   int64
 1   Order ID       9800 non-null   object
 2   Order Date     9800 non-null   object
 3   Ship Date      9800 non-null   object
 4   Ship Mode      9800 non-null   object
 5   Customer ID    9800 non-null   object
 6   Customer Name  9800 non-null   object
 7   Segment        9800 non-null   object
 8   Country        9800 non-null   object
 9   City           9800 non-null   object
 10  State          9800 non-null   object
 11  Postal Code    9789 non-null   float64
 12  Region         9800 non-null   object
 13  Product ID     9800 non-null   object
 14  Category       9800 non-null   object
 15  Sub-Category   9800 non-null   object
 16  Product Name   9800 non-null   object
 17  Sales          9800 non-null   float64
dtypes: float64(2), int64(1), object(15)
memory usage: 1.3+ MB

In [7]:
import pandas as pd

data = pd.read_csv ("/kaggle/input/datasets/ismatkhan121/supermarket-sales-dataset/supermarket.csv")

data.head()

,Row ID,Order ID,Order Date,Ship Date,Ship Mode,Customer ID,Customer Name,Segment,Country,City,State,Postal Code,Region,Product ID,Category,Sub-Category,Product Name,Sales
0,1,CA-2017-152156,08/11/2017,11/11/2017,Second Class,CG-12520,Claire Gute,Consumer,United States,Henderson,Kentucky,42420.0,South,FUR-BO-10001798,Furniture,Bookcases,Bush Somerset Collection Bookcase,261.9600
1,2,CA-2017-152156,08/11/2017,11/11/2017,Second Class,CG-12520,Claire Gute,Consumer,United States,Henderson,Kentucky,42420.0,South,FUR-CH-10000454,Furniture,Chairs,"Hon Deluxe Fabric Upholstered Stacking Chairs,...",731.9400
2,3,CA-2017-138688,12/06/2017,16/06/2017,Second Class,DV-13045,Darrin Van Huff,Corporate,United States,Los Angeles,California,90036.0,West,OFF-LA-10000240,Office Supplies,Labels,Self-Adhesive Address Labels for Typewriters b...,14.6200
3,4,US-2016-108966,11/10/2016,18/10/2016,Standard Class,SO-20335,Sean O'Donnell,Consumer,United States,Fort Lauderdale,Florida,33311.0,South,FUR-TA-10000577,Furniture,Tables,Bretford CR4500 Series Slim Rectangular Table,957.5775
4,5,US-2016-108966,11/10/2016,18/10/2016,Standard Class,SO-20335,Sean O'Donnell,Consumer,United States,Fort Lauderdale,Florida,33311.0,South,OFF-ST-10000760,Office Supplies,Storage,Eldon Fold 'N Roll Cart System,22.3680

In [9]:
import pandas as pd

data = pd.read_csv ("/kaggle/input/datasets/ismatkhan121/supermarket-sales-dataset/supermarket.csv")

data.describe()

            Row ID   Postal Code         Sales
count  9800.000000   9789.000000   9800.000000
mean   4900.500000  55273.322403    230.769059
std    2829.160653  32041.223413    626.651875
min       1.000000   1040.000000      0.444000
25%    2450.750000  23223.000000     17.248000
50%    4900.500000  58103.000000     54.490000
75%    7350.250000  90008.000000    210.605000
max    9800.000000  99301.000000  22638.480000

In [12]:
import pandas as pd

data = pd.read_csv ("/kaggle/input/datasets/ismatkhan121/supermarket-sales-dataset/supermarket.csv")

data.shape

(9800, 18)

## 3. Data Quality Check
Pada tahap ini, kita memeriksa kualitas data, termasuk missing values, duplicate data, tipe data, dan kemungkinan data yang tidak sesuai.

In [17]:
import pandas as pd

data = pd.read_csv ("/kaggle/input/datasets/ismatkhan121/supermarket-sales-dataset/supermarket.csv")

data.isna().sum()

Row ID            0
Order ID          0
Order Date        0
Ship Date         0
Ship Mode         0
Customer ID       0
Customer Name     0
Segment           0
Country           0
City              0
State             0
Postal Code      11
Region            0
Product ID        0
Category          0
Sub-Category      0
Product Name      0
Sales             0
dtype: int64

In [22]:
import pandas as pd

data = pd.read_csv ("/kaggle/input/datasets/ismatkhan121/supermarket-sales-dataset/supermarket.csv")

data.duplicated().sum()

np.int64(0)

In [23]:
import pandas as pd

data = pd.read_csv ("/kaggle/input/datasets/ismatkhan121/supermarket-sales-dataset/supermarket.csv")

data.dtypes

Row ID             int64
Order ID          object
Order Date        object
Ship Date         object
Ship Mode         object
Customer ID       object
Customer Name     object
Segment           object
Country           object
City              object
State             object
Postal Code      float64
Region            object
Product ID        object
Category          object
Sub-Category      object
Product Name      object
Sales            float64
dtype: object

## 4. Sales Analysis

Menganalisis nilai penjualan berdasarkan berbagai karakteristik
yang tersedia dalam dataset.

### 4.1 What is the total sales?

Berapa total nilai Sales dari seluruh data transaksi?

In [21]:
import pandas as pd

data = pd.read_csv ("/kaggle/input/datasets/ismatkhan121/supermarket-sales-dataset/supermarket.csv")

total_sales = data['Sales'].sum()

print(f"Total sales adalah: {total_sales}")

Total sales adalah: 2261536.7827000003

### 4.2 What is the average sales per record?

Berapa rata-rata nilai Sales pada setiap record?

In [22]:
import pandas as pd

data = pd.read_csv ("/kaggle/input/datasets/ismatkhan121/supermarket-sales-dataset/supermarket.csv")

rata_rata = data['Sales'].mean()

print(f"Rata-rata dari Sales adalah: {rata_rata}")

Rata-rata dari Sales adalah: 230.7690594591837

### 4.3 Which category generates the highest sales?

Kategori produk mana yang menghasilkan nilai Sales terbesar?

In [26]:
import pandas as pd

data = pd.read_csv ("/kaggle/input/datasets/ismatkhan121/supermarket-sales-dataset/supermarket.csv")

highest = data.groupby('Category')['Sales'].sum()
nama_kategori = highest.idxmax()
angka_sales = highest.max()
print(f"Kategori terbesar adalah: {nama_kategori}\nDDengan sales sebesar: {angka_sales}")

Kategori terbesar adalah: Technology
DDengan sales sebesar: 827455.873

### 4.4 Which sub-category generates the highest sales?

Sub-category mana yang menghasilkan nilai Sales terbesar?

In [25]:
import pandas as pd

data = pd.read_csv ("/kaggle/input/datasets/ismatkhan121/supermarket-sales-dataset/supermarket.csv")

highest = data.groupby('Sub-Category')['Sales'].sum()
sub_kategori = highest.idxmax()
angka_sales = highest.max()
print(f"Sub-Kategori terbesar adalah: {sub_kategori}\nDengan sales sebesar: {angka_sales}")

Sub-Kategori terbesar adalah: Phones
Dengan sales sebesar: 327782.448

### 4.5 Which products have the highest sales?

Produk individual mana yang memiliki nilai Sales terbesar?

In [24]:
import pandas as pd

data = pd.read_csv ("/kaggle/input/datasets/ismatkhan121/supermarket-sales-dataset/supermarket.csv")

highest = data.groupby('Product Name')['Sales'].sum()
nama_product = highest.idxmax()
angka_sales = highest.max()
print(f"Product terbesar adalah: {nama_product}\nDengan sales sebesar: {angka_sales}")

Product terbesar adalah: Canon imageCLASS 2200 Advanced Copier
Dengan sales sebesar: 61599.824

## 5. Customer & Geographic Analysis

Menganalisis pola penjualan berdasarkan pelanggan dan lokasi.

### 5.1 Which customer generates the highest sales?

Pelanggan mana yang memiliki total Sales terbesar?